source "http://rubygems.org"
gem "rails"
gem 'sqlite3'
gem 'react-rails'
gem 'opal', '~> 0.10.0'
gem 'opal-browser'
gem 'opal-rails'
gem 'therubyracer'
gem 'jquery-cookie-rails'
gem 'byebug'
gem 'pry-rails'
gem 'pry-rescue'
gem 'opal-rspec-rails', github: 'opal/opal-rspec-rails'
gem 'hyper-mesh', path: "../"
gem 'hyper-operation', path: "../../hyper-operation"
gem 'web-console'
gem 'hyper-trace'
gem 'pry'
